services:
  app:
    image: nginx:stable-perl
    volumes:
      - /home/anthony/Dev/Reminder/App/dist/app/browser/:/usr/share/nginx/html/:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: always